build: ## build the web site
	hugo


clean: ## clean the website
	rm -rf dist/*

post: ## post web site
	hugo new posts/$(POST_NAME).md

help: ## Help 
	echo "build: build the website"
	echo "clean: clean the website"
